cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'

brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'postgresql'
brew 'unrar'
brew 'wget'
brew 'nvm'
brew 'svn'

cask 'atom'
cask 'firefox'
cask 'box-sync'
cask 'google-chrome'
cask 'sourcetree'
cask 'docker'
cask 'iterm2'
cask 'slack'
cask 'flux'
cask 'bettertouchtool'
cask 'teamviewer'
cask 'charles'
cask 'silverlight'
cask 'vlc'
